apiVersion: v1
kind: Service
metadata:
  name: sentry-postgres-service
  namespace: cuet-app
  labels:
    app: sentry-postgres
spec:
  type: ClusterIP
  selector:
    app: sentry-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
