apiVersion: v1
kind: Service
metadata:
  name: sentry-service
  namespace: cuet-app
  labels:
    app: sentry
spec:
  type: ClusterIP
  selector:
    app: sentry
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
