apiVersion: v1
kind: Service
metadata:
  name: sentry-redis-service
  namespace: cuet-app
  labels:
    app: sentry-redis
spec:
  type: ClusterIP
  selector:
    app: sentry-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
